### ISSUE TITLE
parallelize or replace pandas apply functions

### ISSUE THREAD

**Issue by nbokulich** [bokulich-lab/RESCRIPt#10]
Some formatting steps in various actions, e.g., `cross-validate` are single-core bottlenecks in pandas.

Should either:
1. Parallelize. Use [swifter](https://github.com/jmcarpenter2/swifter) or dask or something to apply eligible functions in parallel.
2. Replace formats. Some of these steps (e.g., validation in cross-validate) needn't necessarily be done in pandas, but it is convenient. Consider replacing those steps with a more efficient format... e.g., validation could be done by looping over feature IDs with skbio???

**Comment by misialq** [comment]
I had a look at the `apply` actions in the `cross-validate` module and investigated a little using `swifter` for parallelising those, just as a "POC". It seems that swifter/dask does not really perform well when working with string columns: doing some little testing showed that it either takes longer or the same time at best when applying a function to strings rather then numbers (results are averages of 5 runs):

1. Apply some function to a series of 1 mln integers:
- no swifter, just apply: 2.3 sec
- with swifter, auto partitions: 0.024 sec

2. Apply some function to a series of 1 mln strings:
- no swifter, just apply: 2.6 sec
- with swifter, auto partitions: 15.6 sec

Considering that those operations do not take that much time compared to others, I deem it not worthy optimization (since it would take some more effort to parallelise those) and hence am closing this issue.
