### ISSUE TITLE
Include RESCRIPt in qiime docker

### ISSUE THREAD

**Issue by asafpr** [bokulich-lab/RESCRIPt#107]
Not really this package issue but it'll be nice if it will included in the docker, currently qiime rescript doesn't work in quay.io/qiime2/core:2021.4

**Comment by nbokulich** [comment]
thanks for the feedback! this might be something to bring up on the QIIME 2 forum — closing this issue since as you say it is not really specific to this package.

This was just shared via the QIIME 2 forum, I have not tested but it sounds like this is what you are looking for (docker container with QIIME 2 and rescript installed):
https://github.com/gadgrandez/qiime2-rescript

**Comment by thermokarst** [comment]
https://forum.qiime2.org/t/installing-community-plugins-in-docker/7106
